# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: Blacksmithyogi/kernel_build_action@main
      with:
          kernel-url: https://github.com/Blacksmithyogi/kernel_xiaomi_courbet
          kernel-dir: msm-4.14
          kernel-branch: A15
          config: courbet_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: false
          ksu-version: main
          android-version: 15
          aosp-clang-version: r547379
          disable-lto: true
          anykernel3: true
